/**
 * SEO + GEO (Generative Engine Optimization) helpers.
 *
 * Centralizes everything search engines and answer engines (Google, Bing,
 * Perplexity, ChatGPT, Claude, Gemini) need to understand the site:
 *   - canonical URLs + hreflang alternates for the 3 locales,
 *   - JSON-LD structured-data builders (Organization, WebSite, TechArticle,
 *     BreadcrumbList, FAQPage, CollectionPage),
 *   - small content parsers (excerpt, FAQ extraction) that turn MDX into
 *     machine-readable snippets.
 *
 * Pure + framework-agnostic except for the tiny <JsonLd> render helper.
 */
import {
  LOCALES,
  SITE,
  ORG,
  OG_LOCALE,
  type Locale,
} from "@/lib/config";

/** Join a root-relative path onto the canonical site origin. */
export function absoluteUrl(path: string): string {
  return new URL(path, SITE.url).toString();
}

/**
 * The default social/answer-engine preview image, generated by
 * `app/opengraph-image.tsx`. Referenced explicitly because pages set their own
 * `openGraph`, and Next replaces (rather than deep-merges) that field, so the
 * file-convention image must be re-attached wherever `openGraph` is overridden.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${SITE.brand}: ${SITE.tagline}`,
};

/**
 * hreflang alternates for a path that exists in every locale. `pathAfterLocale`
 * is the route *after* the `/<locale>` segment (no leading slash), e.g.
 * "concepts/diamond" or "" for a locale home.
 *
 * Returns absolute URLs keyed by language, plus `x-default` (the primary
 * locale) so engines know which version to show when no language matches.
 */
export function languageAlternates(
  pathAfterLocale: string,
  /**
   * Locales this page actually exists in. Defaults to all of them; pass the
   * real set (see `localesWithDoc`) so the cluster never advertises a
   * translation that 404s. `x-default` follows the first available locale.
   */
  available: readonly Locale[] = LOCALES,
): Record<string, string> {
  const suffix = pathAfterLocale ? `/${pathAfterLocale}` : "";
  const locales = available.length ? available : LOCALES;
  const languages: Record<string, string> = {};
  for (const loc of locales) {
    languages[loc] = absoluteUrl(`/${loc}${suffix}`);
  }
  languages["x-default"] = absoluteUrl(`/${locales[0]}${suffix}`);
  return languages;
}

/** Canonical absolute URL for a locale-scoped path. */
export function canonicalFor(
  locale: Locale,
  pathAfterLocale: string,
): string {
  const suffix = pathAfterLocale ? `/${pathAfterLocale}` : "";
  return absoluteUrl(`/${locale}${suffix}`);
}

/**
 * `alternates` block ready to spread into a Next.js Metadata object:
 * canonical + per-language hreflang.
 */
export function alternatesFor(
  locale: Locale,
  pathAfterLocale: string,
  available?: readonly Locale[],
) {
  return {
    canonical: canonicalFor(locale, pathAfterLocale),
    languages: languageAlternates(pathAfterLocale, available),
  };
}

// ---------------------------------------------------------------------------
// Content → snippet helpers
// ---------------------------------------------------------------------------

/** Strip MDX/markdown syntax down to plain prose (mirrors the search indexer). */
export function toPlainText(body: string): string {
  return body
    .replace(/```[\s\S]*?```/g, " ")
    .replace(/`[^`]*`/g, " ")
    .replace(/^import .*$/gm, " ")
    .replace(/^#{1,6}\s+/gm, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/:::[a-z]*/g, " ")
    .replace(/[*_~>|]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * A ~155-char meta-description fallback derived from the first prose paragraph,
 * for the many docs whose frontmatter omits `description`. Good snippets are a
 * direct CTR lever and feed answer-engine summaries.
 */
export function excerpt(body: string, max = 155): string {
  const text = toPlainText(body);
  // Accumulate sentences, skipping leading section numbers ("1.") and other
  // ultra-short / letter-free fragments that make for useless snippets.
  const sentences = text.split(/(?<=[.!?])\s+/);
  let out = "";
  for (const s of sentences) {
    const clean = s.trim();
    if (!out && (clean.length < 12 || !/[a-zA-Z]{3,}/.test(clean))) continue;
    out = out ? `${out} ${clean}` : clean;
    if (out.length >= max) break;
  }
  if (!out) out = text;
  if (out.length <= max) return out;
  const clipped = out.slice(0, max);
  const lastSpace = clipped.lastIndexOf(" ");
  return `${(lastSpace > 60 ? clipped.slice(0, lastSpace) : clipped).trimEnd()}…`;
}

/**
 * Parse a Q&A-style MDX body into question/answer pairs. Each `###` (or `##`)
 * heading is treated as a question and the prose until the next heading as its
 * answer. Used to emit FAQPage schema from the FAQs doc.
 */
export function extractFaq(body: string): { question: string; answer: string }[] {
  const out: { question: string; answer: string }[] = [];
  const lines = body.split("\n");
  let current: { question: string; answer: string[] } | null = null;
  let inFence = false;

  const push = () => {
    if (current) {
      const answer = toPlainText(current.answer.join("\n"));
      if (current.question && answer) {
        out.push({ question: current.question, answer });
      }
    }
  };

  for (const line of lines) {
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    // Questions are authored either as `##` headings or, on the FAQ pages, as
    // the <summary> of a <details> disclosure. Both must be recognised or the
    // page silently loses its FAQPage rich-result eligibility.
    const summary = inFence ? null : line.match(/<summary[^>]*>\s*(.+?)\s*<\/summary>/);
    const heading =
      inFence || summary ? null : line.match(/^#{2,3}\s+(.+?)\s*#*\s*$/);
    const question = summary?.[1] ?? heading?.[1];
    if (question) {
      push();
      current = { question: question.replace(/[*_`]/g, "").trim(), answer: [] };
    } else if (current) {
      // Structural tags of the disclosure itself aren't part of the answer.
      if (/^\s*<\/?details(\s|>)/.test(line)) continue;
      current.answer.push(line);
    }
  }
  push();
  return out;
}

// ---------------------------------------------------------------------------
// JSON-LD structured-data builders
// ---------------------------------------------------------------------------

type Json = Record<string, unknown>;

const PUBLISHER = {
  "@type": "Organization",
  name: ORG.name,
  url: SITE.siteUrl,
  logo: { "@type": "ImageObject", url: ORG.logo },
} as const;

/** Organization entity that anchors the brand in the knowledge graph. */
export function organizationLd(): Json {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${SITE.siteUrl}/#organization`,
    name: ORG.name,
    legalName: ORG.legalName,
    url: SITE.siteUrl,
    logo: { "@type": "ImageObject", url: ORG.logo },
    description: SITE.description,
    sameAs: [...ORG.sameAs],
  };
}

/**
 * WebSite entity with a SearchAction so engines can surface the docs search box
 * (sitelinks search box). The query template points at the locale home with a
 * `?q=` param the client search reads.
 */
export function websiteLd(locale: Locale): Json {
  const home = canonicalFor(locale, "");
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE.url}/#website`,
    name: SITE.name,
    url: SITE.url,
    description: SITE.description,
    inLanguage: locale,
    publisher: { "@id": `${SITE.siteUrl}/#organization` },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${home}?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  };
}

/** BreadcrumbList from an ordered trail of {name, url?} items. */
export function breadcrumbLd(
  items: { name: string; url?: string }[],
): Json {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      ...(item.url ? { item: item.url } : {}),
    })),
  };
}

/** TechArticle for a documentation page. */
export function articleLd(opts: {
  title: string;
  description: string;
  url: string;
  locale: Locale;
  section: string;
}): Json {
  return {
    "@context": "https://schema.org",
    "@type": "TechArticle",
    headline: opts.title,
    description: opts.description,
    inLanguage: opts.locale,
    mainEntityOfPage: { "@type": "WebPage", "@id": opts.url },
    articleSection: opts.section,
    isPartOf: { "@id": `${SITE.url}/#website` },
    author: PUBLISHER,
    publisher: PUBLISHER,
  };
}


/** FAQPage from extracted Q&A pairs. */
export function faqLd(
  qa: { question: string; answer: string }[],
): Json {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: qa.map(({ question, answer }) => ({
      "@type": "Question",
      name: question,
      acceptedAnswer: { "@type": "Answer", text: answer },
    })),
  };
}

// ---------------------------------------------------------------------------
// Render helper
// ---------------------------------------------------------------------------

/**
 * Inline a JSON-LD payload as a <script type="application/ld+json">. Accepts a
 * single object or an array (emitted as a `@graph`-style list of scripts).
 * Safe in Server Components; content is build-time static.
 */
export function JsonLd({ data }: { data: Json | Json[] }) {
  const blocks = Array.isArray(data) ? data : [data];
  return (
    <>
      {blocks.map((block, i) => (
        <script
          key={i}
          type="application/ld+json"
          // JSON-LD is trusted, build-time content. `</script>` is escaped to
          // avoid breaking out of the tag.
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(block).replace(/</g, "\\u003c"),
          }}
        />
      ))}
    </>
  );
}

/** Locale → Open Graph locale code, with alternates for the other languages. */
export function ogLocale(locale: Locale): { locale: string; alternateLocale: string[] } {
  return {
    locale: OG_LOCALE[locale],
    alternateLocale: LOCALES.filter((l) => l !== locale).map((l) => OG_LOCALE[l]),
  };
}
