import { NextResponse, type NextRequest } from "next/server";
import routes from "@/lib/generated/markdown-routes.json";

/**
 * Agent content negotiation (AFDocs / Agent Score).
 *
 * When a client prefers Markdown over HTML (`Accept: text/markdown`), serve the
 * pre-rendered `.md` twin generated by `scripts/build-markdown.ts` at the same
 * canonical URL — so an agent can fetch `/en/concepts/diamond` and receive clean
 * Markdown, while browsers keep getting HTML. The `.md` URLs are also directly
 * reachable; this only adds same-URL negotiation on top.
 *
 * The rewrite is gated by `markdown-routes.json` (the set of pages that actually
 * have a twin) so non-doc routes — the home page, section landings — fall through
 * to HTML untouched rather than 404'ing on a missing `.md`.
 */
const MD_ROUTES = new Set<string>(routes as string[]);

/** True when the Accept header ranks Markdown at least as high as HTML. */
function prefersMarkdown(accept: string | null): boolean {
  if (!accept) return false;
  let mdQ = -1;
  let htmlQ = -1;
  for (const part of accept.split(",")) {
    const [rawType, ...params] = part.trim().split(";");
    const type = rawType.trim().toLowerCase();
    const qParam = params.find((p) => p.trim().startsWith("q="));
    const q = qParam ? Number.parseFloat(qParam.split("=")[1]) : 1;
    if (type === "text/markdown" || type === "text/x-markdown") {
      mdQ = Math.max(mdQ, Number.isNaN(q) ? 1 : q);
    } else if (type === "text/html" || type === "application/xhtml+xml") {
      htmlQ = Math.max(htmlQ, Number.isNaN(q) ? 1 : q);
    }
  }
  if (mdQ < 0) return false;
  return htmlQ < 0 || mdQ >= htmlQ;
}

export function middleware(req: NextRequest): NextResponse {
  if (!prefersMarkdown(req.headers.get("accept"))) return NextResponse.next();

  const pathname = req.nextUrl.pathname.replace(/\/+$/, "") || "/";
  if (!MD_ROUTES.has(pathname)) return NextResponse.next();

  const url = req.nextUrl.clone();
  url.pathname = `${pathname}.md`;
  return NextResponse.rewrite(url);
}

export const config = {
  // Run on extension-less paths only — skip Next internals, the API, and any
  // request for a static file (including the `.md` twins themselves).
  matcher: ["/((?!_next/|api/|.*\\.).*)"],
};
